import { Recycle, Star, Flame, Scale, Trophy, Award, Sprout, Zap, Target, Cpu } from "lucide-react";
import type { Mission } from "@/types";

export const MISSIONS: Mission[] = [
  { id: "first_log",     title: "Primer paso",            desc: "Registra tu primer reciclaje",            bonus: 50,  icon: Sprout,  check: (l) => l.length >= 1,                                       currentVal: (l) => Math.min(l.length, 1),                                  total: 1    },
  { id: "logs_5",        title: "Reciclador activo",      desc: "Registra 5 reciclajes",                   bonus: 100, icon: Recycle, check: (l) => l.length >= 5,                                       currentVal: (l) => Math.min(l.length, 5),                                  total: 5    },
  { id: "logs_20",       title: "Veterano del reciclaje", desc: "Registra 20 reciclajes",                  bonus: 250, icon: Trophy,  check: (l) => l.length >= 20,                                      currentVal: (l) => Math.min(l.length, 20),                                 total: 20   },
  { id: "kg_5",          title: "5 kg reciclados",        desc: "Recicla 5 kg en total",                   bonus: 75,  icon: Scale,   check: (_l, k) => k >= 5,                                          currentVal: (_l, k) => Math.min(k, 5),                                     total: 5    },
  { id: "kg_10",         title: "10 kg reciclados",       desc: "Recicla 10 kg en total",                  bonus: 150, icon: Scale,   check: (_l, k) => k >= 10,                                         currentVal: (_l, k) => Math.min(k, 10),                                    total: 10   },
  { id: "kg_50",         title: "50 kg reciclados",       desc: "Recicla 50 kg en total",                  bonus: 500, icon: Award,   check: (_l, k) => k >= 50,                                         currentVal: (_l, k) => Math.min(k, 50),                                    total: 50   },
  { id: "streak_3",      title: "Racha de 3 días",        desc: "Mantén una racha de 3 días seguidos",     bonus: 100, icon: Flame,   check: (_l, _k, s) => s >= 3,                                      currentVal: (_l, _k, s) => Math.min(s, 3),                                 total: 3    },
  { id: "streak_7",      title: "Racha de fuego",         desc: "Mantén una racha de 7 días seguidos",     bonus: 200, icon: Flame,   check: (_l, _k, s) => s >= 7,                                      currentVal: (_l, _k, s) => Math.min(s, 7),                                 total: 7    },
  { id: "all_materials", title: "Reciclador completo",    desc: "Recicla todos los tipos de materiales",   bonus: 300, icon: Target,  check: (l) => new Set(l.map((x) => x.material)).size >= 5,         currentVal: (l) => Math.min(new Set(l.map((x) => x.material)).size, 5),   total: 5    },
  { id: "electronics",   title: "E-Waste Warrior",        desc: "Recicla material electrónico",            bonus: 100, icon: Cpu,     check: (l) => l.some((x) => x.material === "electronico"),         currentVal: (l) => (l.some((x) => x.material === "electronico") ? 1 : 0), total: 1    },
  { id: "pts_500",       title: "Eco-Campeón",            desc: "Acumula 500 puntos de reciclaje",         bonus: 150, icon: Star,    check: (_l, _k, _s, p) => p >= 500,                                currentVal: (_l, _k, _s, p) => Math.min(p, 500),                           total: 500  },
  { id: "pts_2000",      title: "Gran Reciclador",        desc: "Acumula 2 000 puntos de reciclaje",       bonus: 500, icon: Zap,     check: (_l, _k, _s, p) => p >= 2000,                               currentVal: (_l, _k, _s, p) => Math.min(p, 2000),                          total: 2000 },
];
